wo:
  de:
    url: www.baidu.com
    name: baidu


# 日志
logging:
  config: classpath:log4j2.properties


spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ENC(/1gzOx/C9dgvNCtvh4QYzw==)
    password: ENC(8rmWL5SE6b88abaLynPmgQ==)
    driver-class-name: com.mysql.jdbc.Driver
    ### 数据源类型durid
    type: com.alibaba.druid.pool.DruidDataSource
    ### 数据库连接池配置
    druid:
      initial-size: 20  # 初始建立连接个数
      min-idle: 5       # 最小连接池数量
      max-active: 150  # 最大连接池数量
      max-wait: 6000   # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      filter: stat,wall,slf4j # 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

# Mybatis配置
mybatis:
  mapper-locations: classpath:com/zxk/springboot/model/mapper/*.xml
#  type-aliases-package: com.zxk.springboot.model

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 盐 (用于配置文件数据加密解密)
jasypt:
    encryptor:
        password: tmg
